apiVersion: v1
kind: Pod
metadata:
  name: pier
spec:
  containers:
  - name: pier
    image: jybwob/pier:v1.23.0
    imagePullPolicy: IfNotPresent
    command: ['pier', 'start']
    # ports:
    # - name: rpc
    #   containerPort: 8545
    volumeMounts:
    - name: pier-0-0
      mountPath: /root/.pier
      readOnly: false

  volumes: #定义一组挂载设备  
    - name: pier-0-0
      hostPath:  
        path: /root/.pier/
        type: Directory