apiVersion: v1
kind: Pod
metadata:
  name: bitxhub
spec:
  containers:
  - name: bitxhub
    image: jybwob/bitxhub-in-one:v5
    imagePullPolicy: IfNotPresent
    command: ['bash', 'cluster.sh']
    args: ['1234']
    ports:
    - name: p1
      containerPort: 60011
    - name: p2
      containerPort: 60012
    - name: p3
      containerPort: 60013
    - name: p4
      containerPort: 60014
    # ports:
    # - name: rpc
    #   containerPort: 8545
  #   volumeMounts:
  #   - name: bitxhub-0-0
  #     mountPath: /root/.pier
  #     readOnly: false

  # volumes: #定义一组挂载设备  
  #   - name: bitxhub-0-0
  #     hostPath:  
  #       path: /root/.pier/
  #       type: Directory